config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  resources :haunted_houses, only: [:show] do
    resources :monsters, only: [:new, :create]
  end
  resources :monsters, only: [:destroy] do
    resources :curses, only: [:new, :create]
  end
end

# /monsters/:monster_id/curses

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/curse.rb
class Curse < ApplicationRecord
  belongs_to :monster # medusa
  belongs_to :power # turn to stone
  validates :monster, uniqueness: { scope: :power }
  # validates :power, uniqueness: { scope: :monster }
end

app/models/haunted_house.rb
class HauntedHouse < ApplicationRecord
  has_many :monsters, dependent: :destroy
  validates :name, presence: true
end

# WITH dd
# haunted_house.destroy # it will destroy all of the monster associated to it

# withOUT dd
# haunted_house.destroy # it will block me from destroying this house

app/models/monster.rb
class Monster < ApplicationRecord
  belongs_to :haunted_house
  has_many :curses, dependent: :destroy  # medusa.curses
  has_many :powers, through: :curses     # medusa.powers
  validates :name, presence: true
  has_one_attached :photo
end

app/models/power.rb
class Power < ApplicationRecord
  has_many :curses
  has_many :monsters, through: :curses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/curses_controller.rb
class CursesController < ApplicationController
  def new
    @monster = Monster.find(params[:monster_id])
    @curse = Curse.new
    # @powers = Power.order(name: :asc)
    # @powers = @monster.powers
    @powers = Power.where.not(id: @monster.powers).order(name: :asc)
  end

  def create
    @monster = Monster.find(params[:monster_id])
    @curse = Curse.new(curse_params)
    @curse.monster = @monster
    if @curse.save
      redirect_to haunted_house_path(@monster.haunted_house)
    else
      render :new
    end
  end

  private

  def curse_params
    params.require(:curse).permit(:power_id)
  end
end

app/controllers/haunted_houses_controller.rb
class HauntedHousesController < ApplicationController
  def show
    @haunted_house = HauntedHouse.find(params[:id])
  end
end

app/controllers/monsters_controller.rb
class MonstersController < ApplicationController
  def new
    @haunted_house = HauntedHouse.find(params[:haunted_house_id])
    @monster = Monster.new
  end

  def create
    @haunted_house = HauntedHouse.find(params[:haunted_house_id])
    @monster = Monster.new(monster_params)
    @monster.haunted_house = @haunted_house
    if @monster.save
      redirect_to haunted_house_path(@haunted_house)
    else
      render :new
    end
  end

  def destroy
    @monster = Monster.find(params[:id])
    @monster.destroy
    redirect_to haunted_house_path(@monster.haunted_house)
  end

  private

  def monster_params
    params.require(:monster).permit(:name, :image_url, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @haunted_houses = HauntedHouse.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/curses_helper.rb
module CursesHelper
end

app/helpers/haunted_houses_helper.rb
module HauntedHousesHelper
end

app/helpers/monsters_helper.rb
module MonstersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/curses/new.html.erb
<div class="container">
  <h1>Curse <%= @monster.name %></h1>
  <%= simple_form_for [@monster, @curse] do |f| %>
    <%= f.association :power, include_blank: false, collection: @powers %>
    <%# , input_html: { multiple: true } %>
    <%= f.submit 'Curse', class: 'btn btn-danger mt-3' %>
  <% end %>
</div>

app/views/haunted_houses/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @haunted_house.banner_url %>);">
  <div class="container">
    <h1><%= @haunted_house.name %></h1>
    <%= link_to 'Add Monster', new_haunted_house_monster_path(@haunted_house), class: 'btn btn-danger mt-2' %>
  </div>
</div>
<div class="container">
  <div class="cards mt-4">
    <% @haunted_house.monsters.each do |monster| %>
      <%= render 'monsters/card', monster: monster %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Haunted795</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/monsters/_card.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= monster.photo.attached? ? cl_image_path(monster.photo.key) : monster.image_url %>)">
  <%= monster.name %>
  <%= link_to monster_path(monster), method: :delete, class: 'card-remove-link', data: { confirm: "Slay #{monster.name}?"} do %>
    <i class="fas fa-cross"></i>
  <% end %>
  <%= link_to new_monster_curse_path(monster), class: 'card-add-link' do %>
    <i class="fas fa-plus"></i>
  <% end %>
  <div class="card-tags">
    <% monster.powers.each do |power| %>
      <span><%= power.name %></span>
    <% end %>
  </div>
</div>

app/views/monsters/new.html.erb
<div class="container mt-5">
  <h1>Spawn Monster</h1>
  <%= simple_form_for [@haunted_house, @monster] do |f| %>
    <%= f.input :name, input_html: { placeholder: 'Monster name'} %>
    <%#= f.input :image_url, input_html: { placeholder: 'www......'} %>
    <%= f.input :photo, as: :file %>
    <%= f.submit 'Spawn', class: 'btn btn-danger mt-3' %>
  <% end %>
</div>

app/views/pages/home.html.erb
<div class="container">
  <h1>Welcome to our Haunted Houses</h1>
  <% @haunted_houses.each do |haunted_house| %>
    <%= link_to haunted_house.name, haunted_house_path(haunted_house)  %>
  <% end %>
</div>